# Generated by Django 4.0.2 on 2022-07-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nhanvat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tennhanvat', models.CharField(max_length=400)),
                ('catinh', models.CharField(max_length=600)),
                ('nhiemvu', models.CharField(max_length=700)),
            ],
        ),
    ]
